---
title: "links"
output: html_document
date: "`r format(Sys.time(), '%Y/%m/%d')`"
---

# 研究用リンク集

## R関連

- [R for Data Science](https://r4ds.had.co.nz/)
- [R Studio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/#ide)
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
- [blogdown](https://bookdown.org/yihui/blogdown/)
- [bookdown](https://pkgs.rstudio.com/bookdown/index.html)
- [Advanced R](https://adv-r.hadley.nz/index.html)
- [Hands-On Programming with R](https://rstudio-education.github.io/hopr/)
- [Applied Statistics with R](https://book.stat420.org/)
- [Modern R with the tidyverse](https://b-rodrigues.github.io/modern_R/)
- [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/)
- [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/)
- [Hands-On Machine Learning with R](https://bradleyboehmke.github.io/HOML/index.html)

### 日本語

- [JIN'S PAGE](https://mjin.doshisha.ac.jp/R/)
- [R-Tips](http://stat.sys.i.kyoto-u.ac.jp/titech/class/doc/r-tips.pdf)
- [RjpWiki](http://www.okadajp.org/RWiki/)
- [Rで計量政治学入門](https://shohei-doi.github.io/quant_polisci/)
- [私たちのR](https://www.jaysong.net/RBook/)
- [からだにいいもの](https://www.karada-good.net/)
- [Kazutan.R](https://kazutan.github.io/kazutanR/index.html)
- [R Markdown クックブック](https://gedevan-aleksizde.github.io/rmarkdown-cookbook/)
- [knitr](https://gedevan-aleksizde.github.io/knitr-doc-ja/index.html)

### visualization関連

- [R CHARTS](https://r-charts.com/)
- [ggplot2](https://ggplot2-book.org/index.html)
- [ComplexHeatmap](https://jokergoo.github.io/ComplexHeatmap-reference/book/)
- [from Data to Vis](https://www.data-to-viz.com/)
- [The R Graph Gallery](https://r-graph-gallery.com/index.html)
- [COLOR BREWER](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3)
- [Statistical tools for high-throughput data analysis](http://www.sthda.com/english/)
- [htmlwidgets for R](http://gallery.htmlwidgets.org/)
- [Data Visualization](https://socviz.co/)
- [ColorsWall](https://colorswall.com/)


## 生物学解析用

- [biopapyrus](https://biopapyrus.jp/)
- [CyTOF workflow](https://www.bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html)
- [Imaging mass cytometry data analysis](https://bodenmillergroup.github.io/IMCDataAnalysis/)
- [gatk](https://gatk.broadinstitute.org/hc/en-us)
- [clusterProfiler](https://yulab-smu.top/biomedical-knowledge-mining-book/index.html)
- [GSEA](http://www.gsea-msigdb.org/gsea/index.jsp)
- [(Rで)塩基配列解析](https://www.iu.a.u-tokyo.ac.jp/~kadota/r_seq.html)
- [Seurat](https://satijalab.org/seurat/index.html)
- [monocle3](https://cole-trapnell-lab.github.io/monocle3/)
- [Signac](https://satijalab.org/signac/index.html)
- [ArchR](https://www.archrproject.com/)
- [scRNA-tools](https://www.scrna-tools.org/)
- [Awesome-single-cell](https://seandavi.github.io/awesome-single-cell/)
- [Metascape](http://metascape.org/gp/index.html#/main/step1)
- [GREAT](http://great.stanford.edu/public/html/)
- [NetMHCpan](https://services.healthtech.dtu.dk/service.php?NetMHCpan-4.1)
- [iDEP](http://bioinformatics.sdstate.edu/idep/)
- [Advanced Single-Cell Analysis with Bioconductor](http://bioconductor.org/books/3.15/OSCA.advanced/)
- [The MEME Suite](https://meme-suite.org/meme/index.html)
- [HOMER](http://homer.ucsd.edu/homer/)

## データベース

### genome関連

- [UCSC Genome Browser](https://genome.ucsc.edu/)
- [GENCODE](https://www.gencodegenes.org/)
- [NCBI](https://www.ncbi.nlm.nih.gov/)
- [HUGO Gene Nomenclature Committee](https://www.genenames.org/)
- [UniProt](https://www.uniprot.org/)


### 遺伝子セット

- [MSigDB](http://www.gsea-msigdb.org/gsea/msigdb/index.jsp)
- [KEGG: Kyoto Encyclopedia of Genes and Genomes](https://www.genome.jp/kegg/kegg_ja.html)
- [reactome](https://reactome.org/)
- [WikiPathways](https://www.wikipathways.org/index.php/WikiPathways)
- [AmiGO 2](http://amigo.geneontology.org/amigo)


### epigenomics関連

- [Cistrome](http://www.cistrome.org/)
- [ChIP-Atlas](https://chip-atlas.org/)
- [ROADMAP epigenomics PROJECT](http://www.roadmapepigenomics.org/)
- [ROADMAP web protal](https://egg2.wustl.edu/roadmap/web_portal/index.html)
- [ENCODE](https://www.encodeproject.org/)


### 転写因子関連

- [JAPAR](https://jaspar.genereg.net/)
- [HumanTFDB](http://bioinfo.life.hust.edu.cn/HumanTFDB#!/)
- [The Human Transcription Factors](http://humantfs.ccbr.utoronto.ca/)


### がん関連

- [COSMIC](https://cancer.sanger.ac.uk/cosmic)
- [cBioPortal](https://www.cbioportal.org/)
- [Genomic Data Commons Data Portal](https://portal.gdc.cancer.gov/)
- [CCLE](https://sites.broadinstitute.org/ccle/)
- [Cell Model Passports](https://cellmodelpassports.sanger.ac.uk/)


### シングルセル関連

- [PanglaoDB](https://panglaodb.se/)
- [HUMAN CELL ATLAS](https://www.humancellatlas.org/)
- [Tabula Sapiens](https://tabula-sapiens-portal.ds.czbiohub.org/)
- [Cross tissue Immune Cell Atlas](https://www.tissueimmunecellatlas.org/)
- [cellxgene](https://cellxgene.cziscience.com/)


### その他

- [FlowRepository](https://flowrepository.org/)
- [RNA-Seq blog](https://www.rna-seqblog.com/)
- [VDJdb](https://vdjdb.cdr3.net/)


---